### ISSUE TITLE
No possibility to pass JSON objects as parameters

### ISSUE THREAD

**Issue by levelboy** [Agilefreaks/weak_swagger_parameters#11]
When defining params, you can only specify the type to be integer, string or boolean.
Because of this, if you try to pass a JSON object to a param, it doesn't get validated so there is no possibility to pass an object like this:

```
{
  "free_trial": 1,
  "campaign_code":"ABC",
  "user": {
    "username":"somebody",
    "password":"easy_peasy"
  },
  "user_profile": {
    ...
  }
}
```

**Comment by pirvudoru** [comment]
Solved in https://github.com/Agilefreaks/weak_swagger_parameters/pull/14
